#!/bin/sh
xrandr --output DisplayPort-0 --primary --mode 1920x1080 --pos 1360x0 --rotate normal --refresh 144.0 --output DisplayPort-1 --mode 1360x768 --pos 3280x0 --rotate normal --output DisplayPort-2 --off --output HDMI-A-0 --mode 1360x768 --pos 0x0 --rotate normal

nitrogen --restore &
picom --config ~/.config/picom/picom.conf
